spring:
  application:
    name: entity
  datasource:
    url: jdbc:postgresql://localhost:5432/ex_modernize
    username: ex_admin
    password: ex_password

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml