#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER docker;
	CREATE DATABASE docker;
	GRANT ALL PRIVILEGES ON DATABASE docker TO docker;

    CREATE USER MD_MASTER;
    CREATE DATABASE MD_DATABASE WITH OWNER = MD_MASTER;

    CREATE USER MD_APP_OWNER;
    CREATE USER MD_SEC_OWNER;
    CREATE USER MD_RPT_OWNER;

    CREATE ROLE MD_ADMIN_ROLE;
    CREATE ROLE MD_ACCOUNTING_ROLE;
    CREATE ROLE MD_GENERAL_LEDGER_ROLE;
    CREATE ROLE MD_ORG_VIEWER_ROLE;
    CREATE ROLE MD_ORG_EDITOR_ROLE;
    CREATE ROLE MD_SEC_APPROVER_ROLE;
EOSQL
