#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER SRV_KEYCLOAK WITH PASSWORD 'secret'; 
	CREATE DATABASE SRV_KEYCLOAK WITH OWNER SRV_KEYCLOAK;
	GRANT ALL PRIVILEGES ON DATABASE SRV_KEYCLOAK TO SRV_KEYCLOAK;
EOSQL

# PGHOST=localhost
# PGPORT=5555
# PGDATABASE=SRV_KEYCLOAK
# PGUSER=SRV_KEYCLOAK
# PGPASSWORD=secret

# psql -v ON_ERROR_STOP=1 --username "$PGUSER" --dbname "$PGDATABASE" --port "$PGPORT" --host "$PGHOST" --no-password <<-EOSQL
# 	CREATE SCHEMA KEYCLOAK AUTHORIZATION SRV_KEYCLOAK;
# 	ALTER ROLE SRV_KEYCLOAK SET SEARCH_PATH TO KEYCLOAK;
# 	DROP SCHEMA PUBLIC;
# EOSQL
