spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:app_modern_demo;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
  test:
    database:
      replace: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/initialize/app-modern-demo.yaml

# logging:
#   level:
#     liquibase: debug